### ISSUE TITLE
Blank Content Types can be added into the grid view

### ISSUE THREAD

**Issue by EdiWang** [waynebaby/Greater-File-Share#3]
RT, it won't cause any issue but the App allow adding empty items to the "Content Types" grid, and there seems to be no way to remove the item.

Suggest to add validation and delete button to the gridview.

**Comment by EdiWang** [comment]
Update: It will blow up after start the hosting:

Values can not be null, Parameter name: key

**Comment by waynebaby** [comment]
Changed behavior, will ignore lines lead to errors. see new logs after start hosting
