### ISSUE TITLE
Tab header in QR page  display wrongly when selected

### ISSUE THREAD

**Issue by waynebaby** [waynebaby/Greater-File-Share#7]
cannot tell differences between activated  Tab and other  Tabs

@EdiWang  Can you take a look at it?

**Comment by EdiWang** [comment]
@waynebaby I am working on this now~

**Comment by EdiWang** [comment]
I am blowing up by a merge conflict. I discard my changes, may be you can do it from your branch. The fix is simple:

Change every header to:

`<TabItem Header="Direct File Address">`

And for the listbox, add 

`BorderBrush="#CCC" BorderThickness="1"`

**Comment by waynebaby** [comment]
fixed
